//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOCAL.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Infos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Infos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOCAL.Messages.Infos", typeof(Infos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hızlı menüye eklendi!.
        /// </summary>
        public static string AddedToQuickMenu {
            get {
                return ResourceManager.GetString("AddedToQuickMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturulan tablonun adını değiştirebilirsiniz..
        /// </summary>
        public static string ChangingCustomTableName {
            get {
                return ResourceManager.GetString("ChangingCustomTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bunu işaretlerseniz revizyon içindeki tüm kısa kodlar mevcut öbekler ile değiştirilecek, revizyon statik hale gelecek ve bundan sonra yapılacak öbek değişikliklerinden etkilenmeyecektir. BU İŞLEM GERİ ALINAMAZ!.
        /// </summary>
        public static string CloseRevisionForUpdatesInfo {
            get {
                return ResourceManager.GetString("CloseRevisionForUpdatesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayar değişikliği için uygulamanın yeninden başlatılması gerekiyor. Uygulamayı yeniden başlatmak istiyor musunuz? (Kaydedilmemiş veriler (varsa) silinecektir.).
        /// </summary>
        public static string ConfirmSettingChange {
            get {
                return ResourceManager.GetString("ConfirmSettingChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanı ile bağlantı kurulamıyor. Lütfen bağlantınızı kontrol ediniz..
        /// </summary>
        public static string ConnectionInvalid {
            get {
                return ResourceManager.GetString("ConnectionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantı testi başarılı!.
        /// </summary>
        public static string ConnectionTestSuccessful {
            get {
                return ResourceManager.GetString("ConnectionTestSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanı başarıyla kaydedildi..
        /// </summary>
        public static string DatabaseHasBeenSaved {
            get {
                return ResourceManager.GetString("DatabaseHasBeenSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; bu parametrenin değeri &lt;b&gt;{1}&lt;/b&gt; &lt;b&gt;{2}&lt;/b&gt; ise &lt;b&gt;{3}&lt;/b&gt; değerini &lt;b&gt;{4}&lt;/b&gt; yap..
        /// </summary>
        public static string DependencyInfo {
            get {
                return ResourceManager.GetString("DependencyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; bu parametrenin değeri &lt;b&gt;{1}&lt;/b&gt; &lt;b&gt;{2}&lt;/b&gt; ise &lt;b&gt;{3}&lt;/b&gt;..
        /// </summary>
        public static string DependencyInfoNoChange {
            get {
                return ResourceManager.GetString("DependencyInfoNoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİLGİ.
        /// </summary>
        public static string DialogTitle {
            get {
                return ResourceManager.GetString("DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu etiket zaten mevcuttur..
        /// </summary>
        public static string DublicateTag {
            get {
                return ResourceManager.GetString("DublicateTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata mesajı {0} adresine gönderiliyor..
        /// </summary>
        public static string ErrorLogIsSending {
            get {
                return ResourceManager.GetString("ErrorLogIsSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulamadan çıkılıyor....
        /// </summary>
        public static string ExitingApplication {
            get {
                return ResourceManager.GetString("ExitingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gmail adresiniz ile e-posta gönderebilmek için Gmail güvenlik ayarınızı değiştirmelisiniz. Gmail sayfasını açmak istiyor musunuz?.
        /// </summary>
        public static string GmailInfo {
            get {
                return ResourceManager.GetString("GmailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu geçmiş kaydı bulunamadı. Başka bir kullanıcı tarafından silinmiş olabilir..
        /// </summary>
        public static string HistoryNoFound {
            get {
                return ResourceManager.GetString("HistoryNoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir resim dosyası seçiniz.
        /// </summary>
        public static string ImageSelectorDescription {
            get {
                return ResourceManager.GetString("ImageSelectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Dosyaları |*.jpg;*.jpeg;*.png.
        /// </summary>
        public static string ImageSelectorFilter {
            get {
                return ResourceManager.GetString("ImageSelectorFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Dosyası Yükleme.
        /// </summary>
        public static string ImageSelectorTitle {
            get {
                return ResourceManager.GetString("ImageSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} yükleniyor....
        /// </summary>
        public static string Loading_ {
            get {
                return ResourceManager.GetString("Loading_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş başarılı. Oturum açılıyor....
        /// </summary>
        public static string LoginSuccessfulSessionIsCreating {
            get {
                return ResourceManager.GetString("LoginSuccessfulSessionIsCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta ayarları başarıyla kaydedildi..
        /// </summary>
        public static string MailConfBeenSaved {
            get {
                return ResourceManager.GetString("MailConfBeenSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta başarıyla gönderildi!.
        /// </summary>
        public static string MailHasBeenSent {
            get {
                return ResourceManager.GetString("MailHasBeenSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta gönderilemedi!.
        /// </summary>
        public static string MailHasNotBeenSent {
            get {
                return ResourceManager.GetString("MailHasNotBeenSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girmiş olduğunuz e-posta adresine bir test e-postası gönderildi. Lütfen gelen kutunuzu ve spam gelen kutunuzu kontrol ediniz..
        /// </summary>
        public static string MailTestSuccessful {
            get {
                return ResourceManager.GetString("MailTestSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt bulunamadı!.
        /// </summary>
        public static string NoRecordsFound {
            get {
                return ResourceManager.GetString("NoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu dokümana ait revizyon kaydedilmemiş..
        /// </summary>
        public static string NoRevisionFound {
            get {
                return ResourceManager.GetString("NoRevisionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kısayol herhangi bir işleme atanmamış..
        /// </summary>
        public static string NotAssignedKey {
            get {
                return ResourceManager.GetString("NotAssignedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturum açılıyor....
        /// </summary>
        public static string OpeningSession {
            get {
                return ResourceManager.GetString("OpeningSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu geçmiş kaydını açmak istiyor musunuz?.
        /// </summary>
        public static string OpenThisHistory {
            get {
                return ResourceManager.GetString("OpenThisHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola gönderilemedi..
        /// </summary>
        public static string PasswordNotSent {
            get {
                return ResourceManager.GetString("PasswordNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parolanız gönderildi..
        /// </summary>
        public static string PasswordSent {
            get {
                return ResourceManager.GetString("PasswordSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir doküman seçiniz.
        /// </summary>
        public static string PleaseChooseDocument {
            get {
                return ResourceManager.GetString("PleaseChooseDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu, hızlı menüde zaten mevcut..
        /// </summary>
        public static string QuickItemAlreadyExist {
            get {
                return ResourceManager.GetString("QuickItemAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt silindi!.
        /// </summary>
        public static string RecordDeleted {
            get {
                return ResourceManager.GetString("RecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formun ilgili verileri ilişkili formlardaki veriler ile eşitlendi..
        /// </summary>
        public static string RecordFormDataHasBeenSynced {
            get {
                return ResourceManager.GetString("RecordFormDataHasBeenSynced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla kaydedildi!.
        /// </summary>
        public static string RecordSaved {
            get {
                return ResourceManager.GetString("RecordSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla güncellendi..
        /// </summary>
        public static string RecordUpdated {
            get {
                return ResourceManager.GetString("RecordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değişiklikleri kaydetmek istiyor musunuz!.
        /// </summary>
        public static string SaveWarning {
            get {
                return ResourceManager.GetString("SaveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturum bilgileri kaydediliyor....
        /// </summary>
        public static string SavingSession {
            get {
                return ResourceManager.GetString("SavingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen örnek bir akıllı kod giriniz. Bu örnek akıllı kod, ilgili parametreleri barındırmalıdır..
        /// </summary>
        public static string SmartCodeSample {
            get {
                return ResourceManager.GetString("SmartCodeSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistem tarafından önerilen kod : .
        /// </summary>
        public static string SuggestedCodeIs {
            get {
                return ResourceManager.GetString("SuggestedCodeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulamadan çıkmak istiyor musunuz? Kaydedilmemiş tüm verilerler (varsa) silinecektir..
        /// </summary>
        public static string SureToClose {
            get {
                return ResourceManager.GetString("SureToClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tablosu başarıyla oluşturuldu, ilgili veriler yüklendi..
        /// </summary>
        public static string TableCreationSuccessful {
            get {
                return ResourceManager.GetString("TableCreationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabloya veri ekleme başarıyla gerçekleştirildi..
        /// </summary>
        public static string TableInsertionSuccessful {
            get {
                return ResourceManager.GetString("TableInsertionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu tablonun kullanımda olduğu bir parametre yoktur..
        /// </summary>
        public static string ThisTableIsNotBeenUsing {
            get {
                return ResourceManager.GetString("ThisTableIsNotBeenUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulamanız günceldir..
        /// </summary>
        public static string UpTodate {
            get {
                return ResourceManager.GetString("UpTodate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı hesap bilgileri gönderiliyor....
        /// </summary>
        public static string UserInfoSending {
            get {
                return ResourceManager.GetString("UserInfoSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Söz dizimi başarılı. {0} adet parametreden değer alınacak. &lt;br&gt;Örnek kod şekli : &lt;b&gt;{1}&lt;/b&gt;.
        /// </summary>
        public static string ValidRegex {
            get {
                return ResourceManager.GetString("ValidRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir doküman türü seçiniz..
        /// </summary>
        public static string WarnNoDocumentTypeSelected {
            get {
                return ResourceManager.GetString("WarnNoDocumentTypeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir klasör seçiniz..
        /// </summary>
        public static string WarnNoFolderSelected {
            get {
                return ResourceManager.GetString("WarnNoFolderSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen {0} diline ait başlığı giriniz..
        /// </summary>
        public static string WarnNoTitleByLang {
            get {
                return ResourceManager.GetString("WarnNoTitleByLang", resourceCulture);
            }
        }
    }
}
