//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOCAL.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StatingStatus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatingStatus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOCAL.Messages.StatingStatus", typeof(StatingStatus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anakart.
        /// </summary>
        public static string BaseBoard {
            get {
                return ResourceManager.GetString("BaseBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapılandırma dosyası kontrol ediliyor....
        /// </summary>
        public static string CheckingConfiguration {
            get {
                return ResourceManager.GetString("CheckingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunucu bağlantısı kontrol ediliyor....
        /// </summary>
        public static string CheckingConnection {
            get {
                return ResourceManager.GetString("CheckingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama dosyaları kontrol ediliyor....
        /// </summary>
        public static string CheckingFiles {
            get {
                return ResourceManager.GetString("CheckingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisans bilgileri kontrol ediliyor....
        /// </summary>
        public static string CheckingLicence {
            get {
                return ResourceManager.GetString("CheckingLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ağ bağlantısı kontrol ediliyor....
        /// </summary>
        public static string CheckingNetwork {
            get {
                return ResourceManager.GetString("CheckingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncellemeler kontrol ediliyor....
        /// </summary>
        public static string CheckingUpdates {
            get {
                return ResourceManager.GetString("CheckingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturum açılıyor....
        /// </summary>
        public static string CreatingSession {
            get {
                return ResourceManager.GetString("CreatingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk Sürücüsü.
        /// </summary>
        public static string DiskDrive {
            get {
                return ResourceManager.GetString("DiskDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diller yükleniyor....
        /// </summary>
        public static string GettingLanguages {
            get {
                return ResourceManager.GetString("GettingLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzinler alınıyor....
        /// </summary>
        public static string GettingPermissions {
            get {
                return ResourceManager.GetString("GettingPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkiler alınıyor....
        /// </summary>
        public static string GettingRoles {
            get {
                return ResourceManager.GetString("GettingRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar yükleniyor....
        /// </summary>
        public static string GettingSettings {
            get {
                return ResourceManager.GetString("GettingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bilgileri yükleniyor....
        /// </summary>
        public static string LoadingWMIStatus {
            get {
                return ResourceManager.GetString("LoadingWMIStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bellek.
        /// </summary>
        public static string MemoryDevice {
            get {
                return ResourceManager.GetString("MemoryDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ağ Bağdaştırıcısı.
        /// </summary>
        public static string NetworkAdapter {
            get {
                return ResourceManager.GetString("NetworkAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiziksel Bellek.
        /// </summary>
        public static string PhysicalMemory {
            get {
                return ResourceManager.GetString("PhysicalMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlemci.
        /// </summary>
        public static string Processor {
            get {
                return ResourceManager.GetString("Processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş yapılıyor....
        /// </summary>
        public static string Signing {
            get {
                return ResourceManager.GetString("Signing", resourceCulture);
            }
        }
    }
}
