//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOCAL.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Warnings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Warnings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOCAL.Messages.Warnings", typeof(Warnings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulumu sonlandırarak çıkmak istiyor musunuz?.
        /// </summary>
        public static string AskForClose {
            get {
                return ResourceManager.GetString("AskForClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu değer zaten mevcut. Güncellemek mi istiyorsunuz?.
        /// </summary>
        public static string AskForDublicate {
            get {
                return ResourceManager.GetString("AskForDublicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kendi hesabınızı silemezsiniz!.
        /// </summary>
        public static string CantDeleteSelf {
            get {
                return ResourceManager.GetString("CantDeleteSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sütun yapılandırması uygun değil. Lütfen kontrol ediniz..
        /// </summary>
        public static string CheckColumns {
            get {
                return ResourceManager.GetString("CheckColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir özellik seçiniz!.
        /// </summary>
        public static string ChooseAProperty {
            get {
                return ResourceManager.GetString("ChooseAProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önce veri türünü seçmelisiniz!.
        /// </summary>
        public static string ChooseDatatypeFirst {
            get {
                return ResourceManager.GetString("ChooseDatatypeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen en az bir yetki seçiniz!.
        /// </summary>
        public static string ChooseRoleWarning {
            get {
                return ResourceManager.GetString("ChooseRoleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçenek listesini temizlemek istiyor musunuz?.
        /// </summary>
        public static string ClearList {
            get {
                return ResourceManager.GetString("ClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapılandırma dosyası bulunamadı!.
        /// </summary>
        public static string ConfigFileNotFound {
            get {
                return ResourceManager.GetString("ConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemden çıkış yapmak istiyor musunuz? (Kullanıcı giriş bilgileri silinecek ve bir sonraki açılışta tekrar giriş yapmanız gerekecektir.).
        /// </summary>
        public static string ConfirmLogout {
            get {
                return ResourceManager.GetString("ConfirmLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ölçüm formunun durum değişikliğini yapmak istiyor musunuz?.
        /// </summary>
        public static string ConfirmStatusUpdate {
            get {
                return ResourceManager.GetString("ConfirmStatusUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantı bilgilerinde sorun var. Lütfen düzeltiniz..
        /// </summary>
        public static string ConnectionBroken {
            get {
                return ResourceManager.GetString("ConnectionBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunucu ile bağlantı kurulamadı!.
        /// </summary>
        public static string ConnectionNotEstablish {
            get {
                return ResourceManager.GetString("ConnectionNotEstablish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu işlem gerçekleştirilemez..
        /// </summary>
        public static string CouldNot {
            get {
                return ResourceManager.GetString("CouldNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanı başarıyla kaydedildi..
        /// </summary>
        public static string DatabaseHasBeenSaved {
            get {
                return ResourceManager.GetString("DatabaseHasBeenSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümünü silmek istediğinizden emin misiniz?.
        /// </summary>
        public static string DeleteAllWarning {
            get {
                return ResourceManager.GetString("DeleteAllWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçili olanları silmek istiyor musunuz?.
        /// </summary>
        public static string DeleteSelectedWarning {
            get {
                return ResourceManager.GetString("DeleteSelectedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydı silmek mi istiyorsunuz? Bu işlem geri alınamayabilir!.
        /// </summary>
        public static string DeleteWarning {
            get {
                return ResourceManager.GetString("DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UYARI.
        /// </summary>
        public static string DialogTitle {
            get {
                return ResourceManager.GetString("DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onaylanmamış değişiklikler olduğundan doküman kaydedilemedi..
        /// </summary>
        public static string DocumentHasNotBeenSavedCauseOfDifferences {
            get {
                return ResourceManager.GetString("DocumentHasNotBeenSavedCauseOfDifferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sütunu için seçili bir özellik yok!.
        /// </summary>
        public static string EmptyColumn {
            get {
                return ResourceManager.GetString("EmptyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} özelliği birden fazla sütun için kullanılmış. Her sütun için ayrı bir özellik seçilmelidir..
        /// </summary>
        public static string ExistingColumn {
            get {
                return ResourceManager.GetString("ExistingColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} adında bir parametre tabloda mevcut. Bunu güncellemek istiyor musunuz?.
        /// </summary>
        public static string ExistingParameter {
            get {
                return ResourceManager.GetString("ExistingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formül ifadesi mevcut değil!.
        /// </summary>
        public static string ExpressionEmpty {
            get {
                return ResourceManager.GetString("ExpressionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanı gereklidir..
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenlemek istediğiniz bu dosya şu an &quot;{0}&quot; tarafından düzenlenmektedir. Bir yanlış olduğunu düşünüyorsanız, kendisi ile irtibata geçiniz..
        /// </summary>
        public static string FileIsInBeingEdittedBy {
            get {
                return ResourceManager.GetString("FileIsInBeingEdittedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya beliritlen adreste bulunamadı..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanı geçersiz..
        /// </summary>
        public static string InvalidDatabase {
            get {
                return ResourceManager.GetString("InvalidDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varsayılan e-posta adresi geçersiz.
        /// </summary>
        public static string InvalidDefaultMail {
            get {
                return ResourceManager.GetString("InvalidDefaultMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisans anahtarı geçersiz. Lütfen kontrol ederek tekrar deneyiniz..
        /// </summary>
        public static string InvalidLicence {
            get {
                return ResourceManager.GetString("InvalidLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta adresi bulunamadı..
        /// </summary>
        public static string InvalidMail {
            get {
                return ResourceManager.GetString("InvalidMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola geçersiz..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz port numarası..
        /// </summary>
        public static string InvalidPort {
            get {
                return ResourceManager.GetString("InvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birincil anahtar parametre ID&apos;si geçersiz..
        /// </summary>
        public static string InvalidPrimaryParameter {
            get {
                return ResourceManager.GetString("InvalidPrimaryParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Söz diziminde hata var..
        /// </summary>
        public static string InvalidRegex {
            get {
                return ResourceManager.GetString("InvalidRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunucu adresi geçersiz..
        /// </summary>
        public static string InvalidServer {
            get {
                return ResourceManager.GetString("InvalidServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı geçersiz..
        /// </summary>
        public static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anahtar parametereler ilişkisel veri alamaz. Elle girilmeli ya da seçilmelidir..
        /// </summary>
        public static string KeyParametersCannotConnect {
            get {
                return ResourceManager.GetString("KeyParametersCannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisans sorunu. Uygulama, bu cihaz için lisanslanmamıştır..
        /// </summary>
        public static string LicenceError {
            get {
                return ResourceManager.GetString("LicenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş yapılamadı. Lütfen bilgileri ve internet bağlantınızı kontrol ediniz..
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı e-posta ile kayıtlı farklı bir kullanıcı mevcuttur. Lütfen değiştiriniz..
        /// </summary>
        public static string MailExist {
            get {
                return ResourceManager.GetString("MailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kişisel e-posta ayarları yapılandırılmadı. Uygulama üzerinden gönderilecek e-postalar, &quot;{0}&quot; kullanıcı adı ile gönderilecek. E-Posta yapılandırmanızı yapmak için tıklayın..
        /// </summary>
        public static string MailSettingsAreEmpty {
            get {
                return ResourceManager.GetString("MailSettingsAreEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta testi başarısız oldu..
        /// </summary>
        public static string MailTestFailed {
            get {
                return ResourceManager.GetString("MailTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanı en fazla {1} karakter olabilir..
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanı en az {1} karakter olabilir..
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} özelliği girilmediğinden kayıt gerçekleşemez!.
        /// </summary>
        public static string MissingField {
            get {
                return ResourceManager.GetString("MissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eşleşme parametrelerinden biri eksik olduğu için bu işlem yapılamaz!.
        /// </summary>
        public static string MissingParameters {
            get {
                return ResourceManager.GetString("MissingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ağ bağlantısı yok!.
        /// </summary>
        public static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akıllı kod türünü seçiniz..
        /// </summary>
        public static string NoSmartCodeType {
            get {
                return ResourceManager.GetString("NoSmartCodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} yetkiniz bulunmamaktadır..
        /// </summary>
        public static string NotPermitted {
            get {
                return ResourceManager.GetString("NotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formül oluşturulabilmesi için parametrenin kaydedilmiş olması gerekmektedir..
        /// </summary>
        public static string ParameterMustBeSavedForExpression {
            get {
                return ResourceManager.GetString("ParameterMustBeSavedForExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlişkilendirilmek istenen parametre veri türleri aynı değil. İki parametre türü de aynı olmalıdır..
        /// </summary>
        public static string ParametersCannotConnected {
            get {
                return ResourceManager.GetString("ParametersCannotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girilen parolalar birbiri ile eşleşmiyor!.
        /// </summary>
        public static string PasswordConfirmWarning {
            get {
                return ResourceManager.GetString("PasswordConfirmWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola boş bırakılamaz.
        /// </summary>
        public static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola gönderilemedi..
        /// </summary>
        public static string PasswordNotSent {
            get {
                return ResourceManager.GetString("PasswordNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parolanız gönderildi..
        /// </summary>
        public static string PasswordSent {
            get {
                return ResourceManager.GetString("PasswordSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girilen iki parola birbiri ile eşleşmemektedir..
        /// </summary>
        public static string PasswordsNotMatch {
            get {
                return ResourceManager.GetString("PasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı telefon numarası ile kayıtlı farklı bir kullanıcı mevcuttur. Lütfen değiştiriniz..
        /// </summary>
        public static string PhoneExist {
            get {
                return ResourceManager.GetString("PhoneExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girilen pin doğru değildir!.
        /// </summary>
        public static string PinDoesNotMatch {
            get {
                return ResourceManager.GetString("PinDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir kayıt seçiniz!.
        /// </summary>
        public static string PleaseChooseARecord {
            get {
                return ResourceManager.GetString("PleaseChooseARecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen {0} seçiniz..
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen akıllı kod parçasını seçiniz ya da oluşturunuz..
        /// </summary>
        public static string PleaseSelectOrCreateSmartCodePart {
            get {
                return ResourceManager.GetString("PleaseSelectOrCreateSmartCodePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önceki işlem devam ediyor....
        /// </summary>
        public static string PreviousProgressHasBeenContinued {
            get {
                return ResourceManager.GetString("PreviousProgressHasBeenContinued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu işlem yapılamaz. Çünkü {0} değerinde bir kayıt mevcuttur. Lütfen {0} değerini değiştirin..
        /// </summary>
        public static string PropertyExistInRecords {
            get {
                return ResourceManager.GetString("PropertyExistInRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş kaydedilemedi!.
        /// </summary>
        public static string RecordHasNotBeenSaved {
            get {
                return ResourceManager.GetString("RecordHasNotBeenSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} parametresine ait {1} değerinde başka bir kayıt mevcuttur. Bu parametreye ait kayıt eşsiz olmalıdır..
        /// </summary>
        public static string RecordMustBeUnique {
            get {
                return ResourceManager.GetString("RecordMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt sistemde bulunamadı..
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapor tasarımcısını kullanabilmek için {0} formuna ait en az bir kayıt bulunmalıdır..
        /// </summary>
        public static string ReportDesignerNoRecord {
            get {
                return ResourceManager.GetString("ReportDesignerNoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} numaralı ölçüm/ölçümler daha önce raporlanmış. Buna rağmen bu ölçümlerin yeniden raporlanmasını istiyorsanız &quot;EVET&quot; düğmesine basınız. Bu ölçümlerin olmadığı raporu almak için &quot;HAYIR&quot; düğmesine basınız..
        /// </summary>
        public static string ReportedRecords {
            get {
                return ResourceManager.GetString("ReportedRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} özellikleri zorunlu olmasına rağmen seçilmemiş. .
        /// </summary>
        public static string RequiredColumnsAreMissing {
            get {
                return ResourceManager.GetString("RequiredColumnsAreMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm değişiklikleri geri almak istiyor musunuz?.
        /// </summary>
        public static string RevertWarning {
            get {
                return ResourceManager.GetString("RevertWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı koda ait başka bir kayıt mevcuttur. Lütfen kodu değiştiriniz..
        /// </summary>
        public static string SameCodeError {
            get {
                return ResourceManager.GetString("SameCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değişiklikleri kaydetmek istiyor musunuz!.
        /// </summary>
        public static string SaveWarning {
            get {
                return ResourceManager.GetString("SaveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; alanı girilmeli/seçilmelidir..
        /// </summary>
        public static string SearchMissingField {
            get {
                return ResourceManager.GetString("SearchMissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama ifadesinde &lt;b&gt;{0}&lt;/b&gt; ve &lt;b&gt;{1}&lt;/b&gt; operatörleri birlikte kullanılamaz!.
        /// </summary>
        public static string SearchPhraseCodingError {
            get {
                return ResourceManager.GetString("SearchPhraseCodingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama ifadesinde &lt;b&gt;{0}&lt;/b&gt; kısmında söz dizimi hatası mevcut! Açılan tırnak kapatılmalıdır..
        /// </summary>
        public static string SearchSyntaxErrorQuotationMarks {
            get {
                return ResourceManager.GetString("SearchSyntaxErrorQuotationMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinmek istenen tablo kullanımdadır. Bu nedenle silinemez. Tabloyu silmek istiyorsanız, tablo ile ilişkili parametreleri düzenlemelisiniz. .
        /// </summary>
        public static string SelectedTableInUsage {
            get {
                return ResourceManager.GetString("SelectedTableInUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunucu bağlantısında sorun oluştu. Lütfen daha sonra tekrar deneyiniz..
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akıllı kod anahtar parametre içermiyor. Bu nedenle yeni giriş oluşturulamıyor..
        /// </summary>
        public static string SmartCodeDoesNotContainKey {
            get {
                return ResourceManager.GetString("SmartCodeDoesNotContainKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bazı veriler kaydedilemedi..
        /// </summary>
        public static string SomeValuesCannotBeRecorded {
            get {
                return ResourceManager.GetString("SomeValuesCannotBeRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanı en fazla {1} karakter olabilir..
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu seçeneği hızlı menüden kaldırmak istiyor musunuz?.
        /// </summary>
        public static string SureToRemoveItem {
            get {
                return ResourceManager.GetString("SureToRemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablo oluşturmada sorun yaşandı..
        /// </summary>
        public static string TableCannotBeCreated {
            get {
                return ResourceManager.GetString("TableCannotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablo oluşturulamadı!&lt;br&gt;{0}.
        /// </summary>
        public static string TableCreationNotSuccessful {
            get {
                return ResourceManager.GetString("TableCreationNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veriler tabloya aktarılamadı!.
        /// </summary>
        public static string TableInsertionNotSuccessful {
            get {
                return ResourceManager.GetString("TableInsertionNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dikkat! Şablon seçimi tüm içeriği temizler. Devam etmek istiyor musunuz?.
        /// </summary>
        public static string TemplateChoosing {
            get {
                return ResourceManager.GetString("TemplateChoosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçeriği ana ekrana sekme olarak göndermek istiyor musunuz?.
        /// </summary>
        public static string TransferWarning {
            get {
                return ResourceManager.GetString("TransferWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı boş bırakılamaz.
        /// </summary>
        public static string UsernameEmpty {
            get {
                return ResourceManager.GetString("UsernameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu isimde bir kullanıcı adı mevcuttur. Aynı kullanıcı adına sahip iki kullanıcı olamaz. Lütfen düzeltiniz..
        /// </summary>
        public static string UsernameExist {
            get {
                return ResourceManager.GetString("UsernameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcının girişine izin verilmiyor..
        /// </summary>
        public static string UserNotAllowed {
            get {
                return ResourceManager.GetString("UserNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı onaylı değil..
        /// </summary>
        public static string UserNotConfirmed {
            get {
                return ResourceManager.GetString("UserNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı sistemde kayıtlı değildir..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyelik koşullarını kabul ediyor musunuz?.
        /// </summary>
        public static string WillYouAgree {
            get {
                return ResourceManager.GetString("WillYouAgree", resourceCulture);
            }
        }
    }
}
