//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOCAL.Objects {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOCAL.Objects.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Sayın &lt;em&gt;{{NAME}}&lt;/em&gt;,&lt;/p&gt;
        ///&lt;p&gt;{{APPLICATION}} giriş bilgileriniz alttaki gibidir :&lt;/p&gt;
        ///&lt;table style=&quot;height: 79px; width: 345px;&quot;&gt;
        ///&lt;tbody&gt;
        ///&lt;tr&gt;
        ///&lt;td style=&quot;width: 134px;&quot;&gt;&lt;strong&gt;Kullanıcı Adı&lt;/strong&gt;&lt;/td&gt;
        ///&lt;td style=&quot;width: 18px;&quot;&gt;&lt;strong&gt;:&lt;/strong&gt;&lt;/td&gt;
        ///&lt;td style=&quot;width: 171px;&quot;&gt;{{USERNAME}}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td style=&quot;width: 134px;&quot;&gt;&lt;strong&gt;Parola&lt;/strong&gt;&lt;/td&gt;
        ///&lt;td style=&quot;width: 18px;&quot;&gt;&lt;strong&gt;:&lt;/strong&gt;&lt;/td&gt;
        ///&lt;td style=&quot;width: 171px;&quot;&gt;{{PASSWORD}}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;/tbody&gt;
        ///&lt;/table&gt;
        ///&lt;p&gt;&lt;em&gt;&lt;s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ForgetPasswordMail {
            get {
                return ResourceManager.GetString("ForgetPasswordMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{APPLICATION}} Şifre Sıfırlama.
        /// </summary>
        public static string ForgetPasswordMailSubject {
            get {
                return ResourceManager.GetString("ForgetPasswordMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Sayın Kullanıcı,&lt;/p&gt;
        ///&lt;p&gt;{{APPLICATION}}na kayıt olduğunuz için teşekkür ederiz. Uygulama giriş bilgileriniz alttaki gibidir :&lt;/p&gt;
        ///&lt;table style=&quot;height: 79px; width: 345px;&quot;&gt;
        ///&lt;tbody&gt;
        ///&lt;tr&gt;
        ///&lt;td style=&quot;width: 134px;&quot;&gt;&lt;strong&gt;Kullanıcı Adı&lt;/strong&gt;&lt;/td&gt;
        ///&lt;td style=&quot;width: 18px;&quot;&gt;&lt;strong&gt;:&lt;/strong&gt;&lt;/td&gt;
        ///&lt;td style=&quot;width: 171px;&quot;&gt;{{USERNAME}}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td style=&quot;width: 134px;&quot;&gt;&lt;strong&gt;Parola&lt;/strong&gt;&lt;/td&gt;
        ///&lt;td style=&quot;width: 18px;&quot;&gt;&lt;strong&gt;:&lt;/strong&gt;&lt;/td&gt;
        ///&lt;td style=&quot;width: 171px;&quot;&gt;{{PASSWORD}}&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RegisterMail {
            get {
                return ResourceManager.GetString("RegisterMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{APPLICATION}} Kullanıcı Kaydı.
        /// </summary>
        public static string RegisterMailSubject {
            get {
                return ResourceManager.GetString("RegisterMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Sayın Yetkili,&lt;/p&gt;
        ///&lt;p&gt;Sütölçer uygulamasından gönderilen destek mesajı attaki gibidir :&lt;/p&gt;
        ///&lt;p&gt;
        ///&lt;strong&gt;
        ///İsim
        ///&lt;/strong&gt;
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///{{NAME}}
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///&lt;strong&gt;
        ///Telefon
        ///&lt;/strong&gt;
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///{{PHONE}}
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///&lt;strong&gt;
        ///Mesaj
        ///&lt;/strong&gt;
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///{{MESSAGE}}
        ///&lt;/p&gt;.
        /// </summary>
        public static string SupportMail {
            get {
                return ResourceManager.GetString("SupportMail", resourceCulture);
            }
        }
    }
}
