//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOCAL.Components {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Buttons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Buttons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOCAL.Components.Buttons", typeof(Buttons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kameradan Ekle.
        /// </summary>
        public static string AddFromCamera {
            get {
                return ResourceManager.GetString("AddFromCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosyadan Ekle.
        /// </summary>
        public static string AddFromFile {
            get {
                return ResourceManager.GetString("AddFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onayla.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sütunları Dağıt.
        /// </summary>
        public static string BestFitColumns {
            get {
                return ResourceManager.GetString("BestFitColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Vazgeç.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum Değiştir.
        /// </summary>
        public static string ChangeStatusType {
            get {
                return ResourceManager.GetString("ChangeStatusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncellemeleri Kontrol Et.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seç.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih Seçiniz.
        /// </summary>
        public static string ChooseDate {
            get {
                return ResourceManager.GetString("ChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        public static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncellemeye Kapat.
        /// </summary>
        public static string CloseRevisionForUpdates {
            get {
                return ResourceManager.GetString("CloseRevisionForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Küçült.
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sütunları Seç.
        /// </summary>
        public static string ColumnSelector {
            get {
                return ResourceManager.GetString("ColumnSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Bitir.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopyala.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluştur.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopyasını Oluştur.
        /// </summary>
        public static string CreateCopy {
            get {
                return ResourceManager.GetString("CreateCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametre Oluştur.
        /// </summary>
        public static string CreateParameter {
            get {
                return ResourceManager.GetString("CreateParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revizyon Oluştur.
        /// </summary>
        public static string CreateRevision {
            get {
                return ResourceManager.GetString("CreateRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özelleştir.
        /// </summary>
        public static string Customize {
            get {
                return ResourceManager.GetString("Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kes.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hepsini Sil.
        /// </summary>
        public static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doküman Aç.
        /// </summary>
        public static string DocumentOpen {
            get {
                return ResourceManager.GetString("DocumentOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Olarak İndir.
        /// </summary>
        public static string DownloadAsExcel {
            get {
                return ResourceManager.GetString("DownloadAsExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Olarak İndir.
        /// </summary>
        public static string DownloadAsPdf {
            get {
                return ResourceManager.GetString("DownloadAsPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çoğalt.
        /// </summary>
        public static string Dublicate {
            get {
                return ResourceManager.GetString("Dublicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        public static string ExportToDocx {
            get {
                return ResourceManager.GetString("ExportToDocx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Sayfası.
        /// </summary>
        public static string ExportToHtml {
            get {
                return ResourceManager.GetString("ExportToHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim.
        /// </summary>
        public static string ExportToImage {
            get {
                return ResourceManager.GetString("ExportToImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string ExportToPdf {
            get {
                return ResourceManager.GetString("ExportToPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel (97-2003).
        /// </summary>
        public static string ExportToXls {
            get {
                return ResourceManager.GetString("ExportToXls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string ExportToXlsx {
            get {
                return ResourceManager.GetString("ExportToXlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Kaydet ve Bitir.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Kurulumu Tamamla.
        /// </summary>
        public static string FinishSetup {
            get {
                return ResourceManager.GetString("FinishSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revizyonları Göster.
        /// </summary>
        public static string GetLastRevisionInfo {
            get {
                return ResourceManager.GetString("GetLastRevisionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümünü Gizle.
        /// </summary>
        public static string HideAll {
            get {
                return ResourceManager.GetString("HideAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçmişten Aç.
        /// </summary>
        public static string HistoryOpen {
            get {
                return ResourceManager.GetString("HistoryOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verileri Yükle.
        /// </summary>
        public static string LoadAllData {
            get {
                return ResourceManager.GetString("LoadAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta Taşı.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İç Dizine Al.
        /// </summary>
        public static string MoveLowDir {
            get {
                return ResourceManager.GetString("MoveLowDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üste Taşı.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üst Dizine Al.
        /// </summary>
        public static string MoveUpDir {
            get {
                return ResourceManager.GetString("MoveUpDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Ekle.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Sekme.
        /// </summary>
        public static string NewTab {
            get {
                return ResourceManager.GetString("NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Sonraki.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonraki Sayfa.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aç.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosyadan Aç.
        /// </summary>
        public static string OpenFromFile {
            get {
                return ResourceManager.GetString("OpenFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editörde Aç.
        /// </summary>
        public static string OpenInEditor {
            get {
                return ResourceManager.GetString("OpenInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametre Düzenleyici.
        /// </summary>
        public static string ParameterDesigner {
            get {
                return ResourceManager.GetString("ParameterDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapıştır.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ön İzleme.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Önceki Sayfa.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birincil Renk.
        /// </summary>
        public static string PrimaryColor {
            get {
                return ResourceManager.GetString("PrimaryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazdırma Kutusu.
        /// </summary>
        public static string PrintDialog {
            get {
                return ResourceManager.GetString("PrintDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazdırma Önizlemesi.
        /// </summary>
        public static string PrintPreview {
            get {
                return ResourceManager.GetString("PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yayınla.
        /// </summary>
        public static string PublishRevision {
            get {
                return ResourceManager.GetString("PublishRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hızlı Yazdır.
        /// </summary>
        public static string QuickPrint {
            get {
                return ResourceManager.GetString("QuickPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenile.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reddet.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaldır.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeniden Adlandır.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapor Tasarımcısı.
        /// </summary>
        public static string ReportDesigner {
            get {
                return ResourceManager.GetString("ReportDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapor Düzenleyici.
        /// </summary>
        public static string ReportsEditor {
            get {
                return ResourceManager.GetString("ReportsEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        public static string ResetChanges {
            get {
                return ResourceManager.GetString("ResetChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görünümü Sıfırla.
        /// </summary>
        public static string ResetLayout {
            get {
                return ResourceManager.GetString("ResetLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revizyon Aç.
        /// </summary>
        public static string RevisionOpen {
            get {
                return ResourceManager.GetString("RevisionOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Uygulamayı Çalıştır.
        /// </summary>
        public static string RunApplication {
            get {
                return ResourceManager.GetString("RunApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet ve Kapa.
        /// </summary>
        public static string SaveAndClose {
            get {
                return ResourceManager.GetString("SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Kaydet ve Devam Et.
        /// </summary>
        public static string SaveAndContinue {
            get {
                return ResourceManager.GetString("SaveAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet ve Yeni.
        /// </summary>
        public static string SaveAndNew {
            get {
                return ResourceManager.GetString("SaveAndNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet Bilgileri Gönder.
        /// </summary>
        public static string SaveAndSendUserInfo {
            get {
                return ResourceManager.GetString("SaveAndSendUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farklı Kaydet.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlı Raporlar.
        /// </summary>
        public static string SavedReports {
            get {
                return ResourceManager.GetString("SavedReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görünümü Kaydet.
        /// </summary>
        public static string SaveLayout {
            get {
                return ResourceManager.GetString("SaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama Yap.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İkincil Renk.
        /// </summary>
        public static string SecondaryColor {
            get {
                return ResourceManager.GetString("SecondaryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümünü Göster.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtreleme.
        /// </summary>
        public static string ShowFilter {
            get {
                return ResourceManager.GetString("ShowFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruplama Kutusu.
        /// </summary>
        public static string ShowGroupBar {
            get {
                return ResourceManager.GetString("ShowGroupBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Revizyonu Göster.
        /// </summary>
        public static string ShowLastRevision {
            get {
                return ResourceManager.GetString("ShowLastRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akıllı Kodları Göster.
        /// </summary>
        public static string ShowSmartCodes {
            get {
                return ResourceManager.GetString("ShowSmartCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başla.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçe Aktarmayı Başlat.
        /// </summary>
        public static string StartImport {
            get {
                return ResourceManager.GetString("StartImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üst.
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yükle.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
    }
}
