//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOCAL.Components {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Images {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOCAL.Components.Images", typeof(Images).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg class=&quot;inline-svg&quot; height=&quot;512&quot; viewBox=&quot;0 0 64 64&quot; width=&quot;512&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;&lt;g id=&quot;Call_and_email&quot; data-name=&quot;Call and email&quot;&gt;&lt;path d=&quot;m15 6v31l18.282-15.103z&quot; fill=&quot;#ff9811&quot;/&gt;&lt;path d=&quot;m42.718 21.897 18.282 15.103v-31z&quot; fill=&quot;#ff9811&quot;/&gt;&lt;path d=&quot;m39.312 24.859a2 2 0 0 1 -2.624 0l-3.406-2.959-18.282 15.1h46l-18.282-15.1z&quot; fill=&quot;#ffa733&quot;/&gt;&lt;path d=&quot;m15 6 18.282 15.9 3.406 2.962a2 2 0 0 0 2.624 0l3.406-2.962 18.282-15.9z&quot; fill=&quot;#ffb655&quot;/&gt;&lt;path d=&quot;m22.565 24.464a2 2 0 0 0 0-2.828l-8.48 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RequestLicence {
            get {
                return ResourceManager.GetString("RequestLicence", resourceCulture);
            }
        }
    }
}
